=== JalalQ/5203-Ticket-Support-XML/schema/ticket.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tickets">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
						
							<!-- Each ticket exactly one issue (original message) associated with it. -->
							<xs:element name="issue">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="subject" type="xs:string" />										
										<xs:element name="issueDescription" type="xs:string" />
										<xs:element name="dateTimeOfIssue" type="xs:dateTime" />
									</xs:sequence>
									
									<xs:attribute name="category" type="ticketCategory" />
									<xs:attribute name="urgent" type="urgency" />
								</xs:complexType>
							</xs:element>
							
							<xs:element name="messages" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										
										<xs:element name="message" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="dateTimeOfMessage" type="xs:dateTime" />										
													<xs:element name="messageContent" type="xs:string" />
												</xs:sequence>
									
												<xs:attribute name="authorUsername" type="xs:token" />
											</xs:complexType>
										</xs:element>

									</xs:sequence>
									<!-- authorUsername and creatorUserName are both of the same type -->
									<xs:attribute name="authorUsername" type="xs:token" />
								</xs:complexType>
							</xs:element>
						
						</xs:sequence>
						
						<!-- With unsignedLong we can create upto 10^21 (Sextillion) unique ids. -->
						<xs:attribute name="id" type="xs:positiveInteger" />
						<xs:attribute name="status" type="xs:string" />
						<xs:attribute name="creatorUserName" type="xs:token" />
					</xs:complexType>
				</xs:element>
				
			
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- ticketCategory is a categorical field. Some representative fields are listed below. -->
	<xs:simpleType name="ticketCategory">
		<xs:restriction base="xs:token">
			<xs:enumeration value="battery" />
			<xs:enumeration value="internet" />
			<xs:enumeration value="software" />
			<xs:enumeration value="printer" />
			<xs:enumeration value="screen" />
		</xs:restriction>
	</xs:simpleType>
	
	
	<!-- urgency is a categorical field. -->
	<xs:simpleType name="urgency">
		<xs:restriction base="xs:token">
			<xs:enumeration value="yes" />
			<xs:enumeration value="no" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="status">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Open" />
			<xs:enumeration value="Closed" />
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== JalalQ/5203-Ticket-Support-XML/XML/ticket.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- XML file storing the details about the tickets - specifically the messages.
	Written by: Jalaluddin Qureshi, Assignment 1 Final. http5203 (Winter 2021), Humber College -->
<!--id - uniquely identified each of the ticket.
    creatorUsername - uniquely identifies the user through his username who created the ticket.
    status - categorical attribute which can one of the two values: Open or Closed-->
<!-- authorUsername uniquely identifies the user who wrote the message-->
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/ticket.xsd">
  <ticket id="1" creatorUserName="karen293" status="Close">
    <issue category="battery" urgent="no">
      <subject>Laptop battery discharging fast</subject>
      <issueDescription>
			My laptop's battery runs out within 30 mins of full charging. I am using the charger provided by the company to me.
      </issueDescription>
      <dateTimeOfIssue>2020-02-22T08:29:12</dateTimeOfIssue>
    </issue>
    <messages>
      <message authorUsername="j.brock">
        <dateTimeOfMessage>2020-02-22T09:03:39</dateTimeOfMessage>
        <messageContent>
				I am sorry to hear about this. Could you please provide me the ID of the laptop issued to you.
        </messageContent>
      </message>
      <message authorUsername="karen293">
        <dateTimeOfMessage>2021-04-05T12:44:06</dateTimeOfMessage>
        <messageContent>The laptop ID is A198.</messageContent>
      </message>
      <message authorUsername="j.brock">
        <dateTimeOfMessage>2021-04-05T15:13:24</dateTimeOfMessage>
        <messageContent>Thank you. If you come down to my office, I would be happy to issue you a new laptop.</messageContent>
      </message>
    </messages>
  </ticket>
  <ticket id="2" status="Open" creatorUserName="jim5">
    <issue category="battery" urgent="no">
      <subject>Internet Connection Issue</subject>
      <issueDescription>
				My laptop's battery runs out within 30 mins of full charging. I am using the charger provided by the company to me.
      </issueDescription>
      <dateTimeOfIssue>2020-03-05T08:29:12</dateTimeOfIssue>
    </issue>
    <messages>
      <message authorUsername="j.brock">
        <dateTimeOfMessage>2020-02-22T09:03:39</dateTimeOfMessage>
        <messageContent>
					I am sorry to hear about this. Could you please provide me the ID of the laptop issued to you.
        </messageContent>
      </message>
    </messages>
  </ticket>
  <ticket id="3" creatorUserName="karen293" status="Open">
    <issue category="internet" urgent="yes">
      <subject>Wi-Fi Connectivity</subject>
      <issueDescription>My Internet has been slow since morning.</issueDescription>
      <dateTimeOfIssue>2021-04-05T14:52:50</dateTimeOfIssue>
    </issue>
  </ticket>
  <ticket id="4" creatorUserName="jim5" status="Open">
    <issue category="printer" urgent="yes">
      <subject>Printer out of Paper</subject>
      <issueDescription>The printer located on the second floor is out of papers.</issueDescription>
      <dateTimeOfIssue>2021-04-05T15:34:04</dateTimeOfIssue>
    </issue>
  </ticket>
</tickets>
