=== JalalQ/5203-Ticket-Support-XML/schema/user.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="user" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
						
							<!-- code structure for empty element with attribute, taken from:
								https://www.w3schools.com/XML/schema_complex_empty.asp -->
							<xs:element name="logInDetails" >
								<xs:complexType>
									 <xs:attribute name="userName" type="xs:token"/>
									 <xs:attribute name="userType" type="userPrivilage" />
									 <xs:attribute name="userPassword" type="md5hash"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="name">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="firstName" type="xs:string" />										
										<xs:element name="middleName" type="xs:string" minOccurs="0" />
										<xs:element name="lastName" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						
						</xs:sequence>

						<xs:attribute name="userEmail" type="email" />
					</xs:complexType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<!-- Custom Data Types -->
	<!-- MD5 password hash is always 32 character long. -->
	<xs:simpleType name="md5hash">
		<xs:restriction base="xs:token">
			<xs:length value="32"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Email regular expression taken from,
	https://regexlib.com/REDetails.aspx?regexp_id=167 -->
	<xs:simpleType name="email">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- userType has one of the two categorical data - admin or client -->
	<xs:simpleType name="userPrivilage">
		<xs:restriction base="xs:token">
			<xs:enumeration value="admin" />
			<xs:enumeration value="client" />
		</xs:restriction>
	</xs:simpleType>
					
</xs:schema>

=== JalalQ/5203-Ticket-Support-XML/XML/user.xml
<?xml version="1.0" encoding="utf-8" ?>

<!-- XML file storing the details of the users for a "support ticket application.
	Written by: Jalaluddin Qureshi, Assignment 1 Final, http5203 (Winter 2021), Humber College -->

<!-- There are two categories of users: admin and clients.
    All users are uniquely identified by their username (equivalent of user ID)	-->

<!-- User passwords are "hashed" and generated using this online tool.
    https://passwordsgenerator.net/md5-hash-generator/ -->

<!-- PLAIN-TEXT PASSWORDS:
     j.brock plain-text password is "****" (3f37)
     karen293 plain-text password is '****" (cc96)
     jim5 plain-text password is "****" (34d6)
     -->
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/user.xsd">
	
	<user userEmail="j.brock@gmail.com">
		<logInDetails userName="j.brock" userType="admin" userPassword="f6432274349b5cb93433f8ed886a3f37"/>
		<name>
			<firstName>John</firstName>
			<lastName>Brock</lastName>
		</name>
	</user>
	
	<user userEmail="karen.s@yahoo.ca">
		<logInDetails userName="karen293" userType="client" userPassword="6b1628b016dff46e6fa35684be6acc96"/>
		<name>
			<firstName>Karen</firstName>
			<middleName>Kate</middleName>
			<lastName>Brown</lastName>
		</name>
	</user>

	<user userEmail="jim89@yahoo.ca">
		<logInDetails userName="jim5" userType="client" userPassword="2a2d595e6ed9a0b24f027f2b63b134d6"/>
		<name>
			<firstName>Jim</firstName>
			<lastName>Clark</lastName>
		</name>
	</user>
	
</users>
